### ISSUE TITLE
do you have demo code?

### ISSUE THREAD

**Issue by dragon1061** [messense/rocketmq-rs#10]
i am use this repository and need demo，thank you

**Comment by messense** [comment]
Currently only producer part is implemented, test cases can be referred as demo (for now): 

https://github.com/messense/rocketmq-rs/blob/b4804c787fe9160f2fd1d78a72cf70ec9903aa05/src/producer/mod.rs#L463-L675

**Comment by dragon1061** [comment]
but consumer has test code，consumer is implemented?
`#[cfg(test)]
mod test {
    use super::{Consumer, ConsumerOptions};
    use crate::message::MessageQueue;

    #[tokio::test]
    async fn test_get_consumer_list() {
        // tracing_subscriber::fmt::init();
        let mut options = ConsumerOptions::default();
        options.set_name_server(vec!["localhost:9876".to_string()]);
        let consumer = Consumer::with_options(options).unwrap();
        let consumer_list = consumer.get_consumer_list("SELF_TEST_TOPIC").await.unwrap();
        assert!(consumer_list.is_empty());
    }`

**Comment by messense** [comment]
consumer is not fully implemented, it's not able to consume messages from brokers yet.

**Comment by dragon1061** [comment]
i find all of the github , but there is no  rocketmq for rust

**Comment by messense** [comment]
Added simple producer example: https://github.com/messense/rocketmq-rs/blob/master/examples/simple_producer.rs
