### ISSUE TITLE
Can we work together?

### ISSUE THREAD

**Issue by aaron-ai** [messense/rocketmq-rs#12]
The RocketMQ community recently released version 5.0, which is mostly based on gRPC and protobuf, and many developers are interested in the rust language. Here is the repo: [rocketmq-clients](https://github.com/apache/rocketmq-clients).

It would be great if we could develop it together.

**Comment by messense** [comment]
Happy to transfer ownership of https://crates.io/crates/rocketmq to you if you can create an account on crates.io.

**Comment by messense** [comment]
Closing as stale.
